import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "./redux-provider";
import Sidebar from "@/components/sidebar/page";
import Header from "./header/page";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";

// Configure fonts
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter", // CSS variable for styling
});
const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${roboto.variable}`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextTopLoader
          showSpinner={false}
          color="#3b82f6"
          height={3}
          crawlSpeed={300}
        />
        <div className="h-16 sticky top-0 z-50 shadow-xl">
          <Header />
        </div>

        <div className="flex h-[calc(100vh-4rem)]">
          <div className="w-60 h-full  flex-shrink-0">
            <Sidebar />
          </div>

          <div className="flex-1 h-full overflow-x-auto">
            <ReduxProvider>{children}</ReduxProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
